### ISSUE TITLE
调用出错

### ISSUE THREAD

**Issue by Ligenmt** [chineseocr/table-ocr#13]
ubuntu系统，执行 python3 table.py -jpgPath test/dd.jpg报:

Traceback (most recent call last):
  File "table.py", line 22, in <module>
    from darknet import  load_net,predict_image,array_to_image
  File "/data/services/table-ocr/darknet.py", line 52, in <module>
    lib = CDLL(darkRoot, RTLD_GLOBAL)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ../darknet/libdarknet.so: cannot open shared object file: No such file or directory

能看看是怎么回事吗

**Comment by Poncgo** [comment]
../darknet/libdarknet.so: cannot open shared object file: No such file or directory

 看这行，要不没下载编译darknet ，要不是路径不对，要不是没权限

**Comment by Ligenmt** [comment]
> ../darknet/libdarknet.so: cannot open shared object file: No such file or directory
> 
> 看这行，要不没下载编译darknet ，要不是路径不对，要不是没权限

感谢！我再检查一下

**Comment by jiangzz1628** [comment]
@Ligenmt 是编译错误吗？我运行git clone https://github.com/pjreddie/darknet.git ../darknet cp Makefile ../darknet cd ../darknet && make出错，然后执行demo出现了一样的错误，您解决了吗

**Comment by Ligenmt** [comment]
> @Ligenmt 是编译错误吗？我运行git clone https://github.com/pjreddie/darknet.git ../darknet cp Makefile ../darknet cd ../darknet && make出错，然后执行demo出现了一样的错误，您解决了吗

我估计是darknet的问题，不太懂这个，我是放弃使用gpu加速，直接跳过去这个问题了，把config.py里的 GPU = True 改成False

**Comment by jiangzz1628** [comment]
> > @ligenmt是编译错误吗？我运行git clone https://github.com/pjreddie/darknet.git ../darknet cp Makefile ../darknet cd ../darknet && make错误，然后执行demo出现了一样的错误，您解决了吗
> 
> 我估计是darknet的问题，不太懂这个，我是放弃使用gpu加速，直接跳过去这个问题了，把config.py里的GPU = True改成False

好的，谢谢
