### ISSUE TITLE
无表格线表格解析

### ISSUE THREAD

**Issue by leyiwang** [chineseocr/table-ocr#21]
支持无表格线表格的解析吗？

**Comment by wenlihaoyu** [comment]
咱不支持

**Comment by PC-god** [comment]
无表格线 表格解析，比赛里有这个项目，ICDAR 2019 Deep Splitting and Merging for Table Structure Decomposition
table-ocr 作者这个项目效果已经 很好了。就是 不知道 用的什么数据训练的。
